/**
 * Example project: one-story wood-framed residence, 24 ft deep, raised floor.
 * Rafters with a ridge board tied by the ceiling joists, a window header
 * carrying the rafter and ceiling joist reactions, floor joists on a girder,
 * and an I-joist floor bay; a rear porch roof on a ledger and a steel beam on
 * HSS posts with base plates and pads; shear walls (one FTAO wall) on four
 * wall lines with roof diaphragms, a shear-transfer connection and the uplift
 * path. Used for first-run, tests and the help sheet.
 */

import { defaultHardware } from "../data/hardware";
import { defaultAssemblies } from "../loads/dead";
import { defaultLateral, generateWeights } from "./lateral";
import { DEFAULT_MARKS } from "./marks";
import type { Project } from "./schema";
import { loadVector } from "../core/loads";

export function newProject(name = "New project"): Project {
  const p: Project = {
    schemaVersion: 1,
    info: {
      name,
      address: "",
      jobRef: "",
      client: "",
      jurisdiction: "",
      preparedBy: "",
      checkedBy: "",
      approvedBy: "",
      date: "",
      revision: "0",
    },
    cycleId: "2025",
    criteria: {
      riskCategory: "II",
      liveBasis: "IRC",
      roofLive: { L0: 20, reduce: false },
      snow: { pg: 0, Ce: 1.0, Ct: 1.0, Is: 1.0, slippery: false },
      Kcr: 1.0,
      seismic: { SDS: 1.0, SD1: 0.6, siteClass: "D (default)", SDC: "D" },
      wind: { V: 95, exposure: "B", Kzt: 1.0 },
      soil: {
        bearing: 1500,
        source: "Presumptive, CBC Table 1806.2, Class 5 — verify with geotechnical report",
        class: "5",
        density: 110,
      },
      concrete: { fc: 2500, fy: 60000, cover: 3 },
    },
    assemblies: defaultAssemblies(),
    structures: [
      {
        id: "S1",
        name: "Main house",
        levels: [
          { id: "L1", name: "First floor", number: 1 },
          { id: "RF", name: "Roof", number: 2 },
        ],
      },
    ],
    members: [],
    marks: { ...DEFAULT_MARKS },
    hardware: defaultHardware(),
    lateral: undefined,
    drawings: [],
    review: [],
    notes: "",
  };
  p.lateral = defaultLateral(p);
  return p;
}

export function exampleProject(): Project {
  const p = newProject("Example Residence");
  p.info = {
    ...p.info,
    address: "123 Example Street, Escondido, CA",
    jobRef: "HC-0001",
    client: "Example Owner",
    jurisdiction: "City of Escondido",
    date: "2026-10-07",
  };
  p.members = [
    {
      kind: "rafter",
      id: "m-r1",
      mark: "R-1",
      description: "Main roof rafters, ridge board, tied by CJ-1",
      structureId: "S1",
      levelId: "RF",
      status: "new",
      links: [],
      species: "DF-L",
      grade: "No.2",
      size: "2x8",
      spacing: 24,
      rise: 4,
      run: 12,
      overhang: 1.5,
      ridge: "board",
      plateSeat: 5.5,
      ridgeSeat: 0,
      seatCut: 1.5,
      dead: { assemblyId: "RD1" },
      roofLive: true,
      snow: true,
      windPressure: -20,
      deflection: { preset: "roof-nonplaster" },
      luBottom: 4,
      rule441: false,
      tieSpacing: 24,
      gable: true,
    },
    {
      kind: "ceilingJoist",
      id: "m-cj1",
      mark: "CJ-1",
      description: "Ceiling joists / rafter ties, lapped over the center bearing wall",
      structureId: "S1",
      levelId: "RF",
      status: "new",
      links: [],
      species: "DF-L",
      grade: "No.2",
      size: "2x6",
      spacing: 24,
      spans: [12, 12],
      dead: { assemblyId: "CD1" },
      live: { use: "attic-no-storage" },
      extra: [],
      bearing: [5.5, 3.5, 5.5],
      deflection: { preset: "roof-nonplaster" },
      luTop: 0,
      rule441: true,
      tensionFrom: "m-r1",
      heel: { nail: "16d-common", count: 8, rafterThickness: 1.5 },
    },
    {
      kind: "beam",
      id: "m-h1",
      mark: "H-1",
      description: "Window header, exterior bearing wall",
      structureId: "S1",
      levelId: "L1",
      status: "new",
      links: [
        { id: "k1", kind: "line", sourceId: "m-r1", support: 0, label: "Rafters", factor: 1 },
        { id: "k2", kind: "line", sourceId: "m-cj1", support: 0, label: "Ceiling joists", factor: 1 },
      ],
      role: "header",
      material: { kind: "sawn", species: "DF-L", grade: "No.2", size: "4x8", plies: 1 },
      spans: [6],
      area: [],
      walls: [],
      extra: [],
      bearing: [3, 3],
      luTop: 0,
      luBottom: 0,
      deflection: { preset: "roof-nonplaster" },
      selfWeight: true,
    },
    {
      kind: "joist",
      id: "m-fj1",
      mark: "FJ-1",
      description: "Raised floor joists",
      structureId: "S1",
      levelId: "L1",
      status: "new",
      links: [],
      species: "DF-L",
      grade: "No.2",
      size: "2x10",
      spacing: 16,
      spans: [12],
      dead: { assemblyId: "FD1" },
      live: { use: "living" },
      extra: [],
      bearing: [1.5, 1.5],
      luBottom: 0,
      rule441: false,
      deflection: { preset: "floor" },
    },
    {
      kind: "beam",
      id: "m-b1",
      mark: "B-1",
      description: "Family room floor girder: interior post P-1 to perimeter footing F-1",
      structureId: "S1",
      levelId: "L1",
      status: "new",
      links: [{ id: "k3", kind: "line", sourceId: "m-ij1", support: 1, label: "I-joists", factor: 1 }],
      role: "beam",
      material: { kind: "sawn", species: "DF-L", grade: "No.1", size: "4x12", plies: 1 },
      spans: [6],
      area: [],
      walls: [],
      extra: [],
      bearing: [3.5, 3.5],
      luTop: 0,
      luBottom: 0,
      deflection: { preset: "floor" },
      selfWeight: true,
    },
    {
      kind: "ijoist",
      id: "m-ij1",
      mark: "IJ-1",
      description: "Family room I-joist bay, bearing on F-1 and girder B-1",
      structureId: "S1",
      levelId: "L1",
      status: "new",
      links: [],
      series: "TJI 210",
      depth: '11-7/8"',
      spacing: 16,
      spans: [16],
      dead: { assemblyId: "FD1" },
      live: { use: "living" },
      extra: [],
      bearing: [1.75, 3.5],
      deflection: { preset: "floor" },
    },
  ];
  const L = (id: string, sourceId: string, support: number, label: string, x1?: number, x2?: number, factor = 1) => ({
    id,
    kind: "line" as const,
    sourceId,
    support,
    label,
    x1,
    x2,
    factor,
  });
  const P = (id: string, sourceId: string, support: number, label: string, x: number) => ({
    id,
    kind: "point" as const,
    sourceId,
    support,
    label,
    x,
    factor: 1,
  });
  const base = { structureId: "S1", levelId: "L1", status: "new" as const };
  const sill = { type: "cast-in" as const, d: 0.625, spacing: 48, embed: 7, edge: 1.75 };
  const sw = (
    id: string,
    mark: string,
    lineId: string,
    b: number,
    description: string,
    top: number,
    links: ReturnType<typeof L>[],
    holdownId: string,
  ) => ({
    kind: "shearWall" as const,
    id,
    mark,
    description,
    ...base,
    links,
    lineId,
    b,
    h: 9,
    sides: [{ key: "SI-15/32-8d", spacing: 6 }],
    stud: { species: "DF-L" as const, grade: "No.2" as const, size: "2x6", spacing: 16 },
    endPost: { size: "2x6", plies: 2, holeDia: 0.75 },
    top: { D: top, L: 0, Lr: 0, S: 0 },
    self: { assemblyId: "WD1" },
    overturning: "full" as const,
    holdownId,
    sill,
    sillSize: "2x6",
    windService: { factor: 0.42, limitN: 600 },
  });
  p.members.push(
    {
      kind: "wall",
      id: "m-w1",
      mark: "1W-1",
      description: "Front exterior bearing wall with window W1 (H-1)",
      ...base,
      links: [
        L("k10", "m-r1", 0, "Rafters", 0, 4),
        L("k11", "m-r1", 0, "Rafters", 10, 40),
        L("k12", "m-cj1", 0, "Ceiling joists", 0, 4),
        L("k13", "m-cj1", 0, "Ceiling joists", 10, 40),
        P("k14", "m-h1", 0, "Header", 4),
        P("k15", "m-h1", 1, "Header", 10),
      ],
      species: "DF-L",
      grade: "Stud",
      size: "2x6",
      spacing: 16,
      plateHeight: 9,
      topPlates: 2,
      bottomPlates: 1,
      length: 40,
      sheathing: "both",
      self: { assemblyId: "WD1" },
      area: [],
      walls: [],
      extra: [],
      wind: { mode: "computed", zone: 4 },
      deflN: 240,
      packs: [
        { x: 4, studs: 2, label: "Jack + king studs, W1 left" },
        { x: 10, studs: 2, label: "Jack + king studs, W1 right" },
      ],
      openings: [{ label: "Window W1", x1: 4, x2: 10, kings: 1 }],
    },
    {
      kind: "wall",
      id: "m-w2",
      mark: "1W-2",
      description: "Interior bearing wall at the ceiling-joist lap",
      ...base,
      links: [L("k20", "m-cj1", 1, "Ceiling joists")],
      species: "DF-L",
      grade: "Stud",
      size: "2x4",
      spacing: 16,
      plateHeight: 9,
      topPlates: 2,
      bottomPlates: 1,
      length: 40,
      sheathing: "both",
      self: { assemblyId: "WD2" },
      area: [],
      walls: [],
      extra: [],
      wind: { mode: "none" },
      deflN: 240,
      packs: [],
      openings: [],
    },
    {
      kind: "wall",
      id: "m-w3",
      mark: "1W-3",
      description: "Rear exterior bearing wall",
      ...base,
      links: [L("k16", "m-r1", 0, "Rafters"), L("k17", "m-cj1", 2, "Ceiling joists")],
      species: "DF-L",
      grade: "Stud",
      size: "2x6",
      spacing: 16,
      plateHeight: 9,
      topPlates: 2,
      bottomPlates: 1,
      length: 40,
      sheathing: "both",
      self: { assemblyId: "WD1" },
      area: [],
      walls: [],
      extra: [],
      wind: { mode: "computed", zone: 4 },
      deflN: 240,
      packs: [],
      openings: [],
    },
    {
      kind: "connector",
      id: "m-cn1",
      mark: "CN-1",
      description: "Rafter-to-plate tie for wind uplift",
      structureId: "S1",
      levelId: "RF",
      status: "new",
      links: [],
      hardwareId: "H2.5A",
      quantity: 1,
      sourceId: "m-r1",
      support: 0,
    },
    {
      kind: "post",
      id: "m-p1",
      mark: "P-1",
      description: "Crawl-space post under girder B-1",
      ...base,
      links: [P("k30", "m-b1", 0, "Girder", 0)],
      material: { kind: "sawn", species: "DF-L", grade: "No.1", size: "4x4", plies: 1 },
      height: 2.5,
      Ke: 1,
      extra: [],
      bearing: { on: "concrete" },
      selfWeight: true,
    },
    {
      kind: "footing",
      id: "m-pf1",
      mark: "PF-1",
      description: "Pier pad under P-1",
      ...base,
      links: [P("k40", "m-p1", 0, "Post", 0)],
      type: "pad",
      B: 1.5,
      L: 1.5,
      h: 12,
      depth: 18,
      soilOver: 6,
      c1: 3.5,
      c2: 3.5,
      extra: [],
      stories: 1,
    },
    {
      kind: "footing",
      id: "m-f1",
      mark: "F-1",
      description: "Perimeter footing and stem wall, front (Line 1)",
      ...base,
      links: [
        L("k50", "m-w1", 0, "Bearing wall"),
        P("k51", "m-w1", 1, "Stud pack", 4),
        P("k52", "m-w1", 2, "Stud pack", 10),
        L("k53", "m-fj1", 0, "Floor joists", 0, 24),
        L("k54", "m-ij1", 0, "I-joists", 24, 40),
        P("k55", "m-b1", 1, "Girder", 30),
      ],
      type: "strip",
      B: 1.25,
      h: 12,
      depth: 18,
      soilOver: 6,
      c1: 6,
      stem: { width: 6, height: 18 },
      longitudinal: { size: "#4", top: 1, bottom: 1 },
      extra: [],
      stories: 1,
    },
    {
      kind: "footing",
      id: "m-f2",
      mark: "F-2",
      description: "Interior footing and stem wall under 1W-2",
      ...base,
      links: [L("k60", "m-w2", 0, "Bearing wall"), L("k61", "m-fj1", 1, "Floor joists both sides", 0, 24, 2)],
      type: "strip",
      B: 1.25,
      h: 12,
      depth: 18,
      soilOver: 6,
      c1: 6,
      stem: { width: 6, height: 18 },
      longitudinal: { size: "#4", top: 1, bottom: 1 },
      extra: [],
      stories: 1,
    },
    {
      kind: "footing",
      id: "m-f3",
      mark: "F-3",
      description: "Perimeter footing and stem wall, rear (Line 2)",
      ...base,
      links: [L("k62", "m-w3", 0, "Bearing wall"), L("k63", "m-fj1", 0, "Floor joists", 0, 24)],
      type: "strip",
      B: 1.25,
      h: 12,
      depth: 18,
      soilOver: 6,
      c1: 6,
      stem: { width: 6, height: 18 },
      longitudinal: { size: "#4", top: 1, bottom: 1 },
      extra: [],
      stories: 1,
    },
    sw(
      "m-sw1",
      "1SW-1",
      "LN1",
      12,
      "Front wall, right of window W1",
      0,
      [L("k70", "m-r1", 0, "Rafters"), L("k71", "m-cj1", 0, "Ceiling joists")],
      "HDU2-SDS2.5",
    ),
    sw(
      "m-sw2",
      "1SW-2",
      "LN1",
      14,
      "Front wall, right end",
      0,
      [L("k72", "m-r1", 0, "Rafters"), L("k73", "m-cj1", 0, "Ceiling joists")],
      "HDU2-SDS2.5",
    ),
    sw(
      "m-sw3",
      "1SW-3",
      "LN2",
      24,
      "Rear wall",
      0,
      [L("k74", "m-r1", 0, "Rafters"), L("k75", "m-cj1", 0, "Ceiling joists")],
      "HDU2-SDS2.5",
    ),
    sw("m-sw4", "1SW-4", "LNA", 16, "Left gable-end wall", 60, [], "HDU2-SDS2.5"),
    sw("m-sw5", "1SW-5", "LNB", 16, "Right gable-end wall", 60, [], "HDU2-SDS2.5"),
  );
  // rear porch: rafters from a ledger on the house wall to a steel beam on two HSS posts
  const porch = { structureId: "S1", levelId: "L1", status: "new" as const };
  p.members.push(
    {
      kind: "rafter",
      id: "m-r2",
      mark: "R-2",
      description: "Rear porch rafters, ledger to steel beam SB-1",
      structureId: "S1",
      levelId: "RF",
      status: "new",
      links: [],
      species: "DF-L",
      grade: "No.2",
      size: "2x6",
      spacing: 24,
      rise: 3,
      run: 8,
      overhang: 1,
      ridge: "beam",
      plateSeat: 3.5,
      ridgeSeat: 1.5,
      seatCut: 0,
      dead: { assemblyId: "RD1" },
      roofLive: true,
      snow: true,
      deflection: { preset: "roof-nonplaster" },
      luBottom: 4,
      rule441: false,
      gable: false,
    },
    {
      kind: "ledger",
      id: "m-lg1",
      mark: "LG-1",
      description: "Porch ledger on the rear wall framing",
      ...porch,
      links: [L("k80", "m-r2", 1, "Porch rafters")],
      ledger: { species: "DF-L", grade: "No.2", size: "2x8" },
      extra: [],
      lateral: { W: 0, E: 0 },
      fastener: { type: "lag", D: 0.5, Fyb: 45000, spacing: 16, label: "1/2 in. lag screws" },
      support: { kind: "wood", species: "DF-L", thickness: 3 },
      continuity: 1.25,
    },
    {
      kind: "steelBeam",
      id: "m-sb1",
      mark: "SB-1",
      description: "Rear porch beam",
      ...porch,
      links: [L("k81", "m-r2", 0, "Porch rafters")],
      role: "beam",
      shape: "W8x10",
      grade: "A992",
      method: "LRFD",
      spans: [16],
      area: [],
      walls: [],
      extra: [],
      Lb: 2,
      deflection: { preset: "roof-nonplaster" },
      selfWeight: true,
      bearing: [
        { lb: 4, support: "steel" },
        { lb: 4, support: "steel" },
      ],
    },
    ...[0, 1].map((k) => ({
      kind: "steelColumn" as const,
      id: `m-sc${k + 1}`,
      mark: `SC-${k + 1}`,
      description: `Porch post, ${k ? "right" : "left"} end of SB-1`,
      ...porch,
      links: [P(`k82${k}`, "m-sb1", k, "Steel beam", 0)],
      shape: "HSS4x4x1/4",
      grade: "A500C",
      method: "LRFD" as const,
      height: 9,
      Kx: 1,
      Ky: 1,
      extra: [],
      ex: 0,
      ey: 0,
      wind: { psf: 20, width: 1 },
      selfWeight: true,
    })),
    ...[0, 1].map((k) => ({
      kind: "basePlate" as const,
      id: `m-bp${k + 1}`,
      mark: `BP-${k + 1}`,
      description: `Base plate of SC-${k + 1}`,
      ...porch,
      links: [],
      method: "LRFD" as const,
      sourceId: `m-sc${k + 1}`,
      column: "HSS4x4x1/4",
      P: loadVector({}),
      M: loadVector({}),
      V: loadVector({}),
      plate: { N: 10, B: 10, tp: 0.5, grade: "A36-PL" },
      rod: {
        d: 0.625,
        steel: 0,
        nx: 2,
        ny: 2,
        sx: 6,
        sy: 6,
        e1: 2,
        hef: 7,
        type: "headed" as const,
        Abrg: 0.7,
        eh: 3,
        washer: 0,
        groutPad: false,
      },
      foundation: {
        edges: [9, 9, 9, 9] as [number, number, number, number],
        ha: 12,
        cracked: true,
        condition: "B" as const,
      },
      weld: { w: 0.1875, FEXX: 70 },
    })),
    ...[0, 1].map((k) => ({
      kind: "footing" as const,
      id: `m-pf${k + 2}`,
      mark: `PF-${k + 2}`,
      description: `Pad under SC-${k + 1} / BP-${k + 1}`,
      ...porch,
      links: [P(`k84${k}`, `m-bp${k + 1}`, 0, "Steel post", 0)],
      type: "pad" as const,
      B: 1.5,
      L: 1.5,
      h: 12,
      depth: 18,
      soilOver: 0,
      c1: 10,
      c2: 10,
      extra: [],
      stories: 1,
    })),
    {
      kind: "diaphragm",
      id: "m-rd1",
      mark: "RD-1",
      description: "Roof diaphragm, X-direction load",
      structureId: "S1",
      levelId: "RF",
      status: "new",
      links: [],
      level: "roof",
      storyId: "ST1",
      dir: "X",
      sheathing: "SH-15/32-8d",
      blocked: false,
      edge: "6/6",
      unblockedCase: 1,
      chord: { species: "DF-L", grade: "No.2", size: "2x6", splice: { type: "nails", nail: "16d-common", nails: 12 } },
      collectorOmega: false,
    },
    {
      kind: "diaphragm",
      id: "m-rd2",
      mark: "RD-2",
      description: "Roof diaphragm, Y-direction load",
      structureId: "S1",
      levelId: "RF",
      status: "new",
      links: [],
      level: "roof",
      storyId: "ST1",
      dir: "Y",
      sheathing: "SH-15/32-8d",
      blocked: false,
      edge: "6/6",
      unblockedCase: 2,
      chord: { species: "DF-L", grade: "No.2", size: "2x6", splice: { type: "nails", nail: "16d-common", nails: 12 } },
      collectorOmega: false,
    },
    {
      kind: "transfer",
      id: "m-st1",
      mark: "ST-1",
      description: "Roof blocking to top plate over 1SW-3",
      structureId: "S1",
      levelId: "RF",
      status: "new",
      links: [],
      interface: "diaphragm-to-wall",
      source: { kind: "wall", id: "m-sw3" },
      connector: { type: "nails", nail: "16d-common", ts: 1.5, tm: 3, species: "DF-L", toenail: true, rows: 1 },
      spacing: 6,
    },
    {
      kind: "uplift",
      id: "m-up1",
      mark: "UP-1",
      description: "Main roof uplift, rafter to foundation",
      structureId: "S1",
      levelId: "RF",
      status: "new",
      links: [],
      sourceId: "m-r1",
      support: 0,
      levels: [
        {
          label: "Rafter to top plate",
          deadAbove: 0,
          connector: { type: "hardware", hardwareId: "H2.5A" },
          spacing: 24,
        },
        {
          label: "Top plate to sill (stud strap)",
          deadAbove: 0,
          connector: { type: "hardware", hardwareId: "CS16" },
          spacing: 48,
        },
      ],
    },
  );
  const sw1 = p.members.find((m) => m.id === "m-sw1");
  if (sw1?.kind === "shearWall") {
    // force transfer around window W1 (4–10 ft), head 6 ft 8 in., sill 3 ft
    sw1.description = "Front wall from the left corner through window W1 (FTAO)";
    sw1.b = 22;
    sw1.x = 0;
    sw1.opening = { L1: 4, Lo: 6, L2: 12, ha: 2.33, hb: 3, strapId: "CS16" };
  }
  const xs: Record<string, number> = { "m-sw2": 26, "m-sw3": 8, "m-sw4": 4, "m-sw5": 4 };
  for (const m of p.members) if (m.kind === "shearWall" && xs[m.id] !== undefined) m.x = xs[m.id];
  if (sw1?.kind === "shearWall")
    sw1.holdownAnchor = {
      d: 0.625,
      steel: "ASTM F1554 Grade 36",
      hef: 10,
      edges: [7.5, 7.5, 30, 30],
      plate: 2,
      cracked: true,
      omega: true,
    };
  p.lateral = {
    ...defaultLateral(p),
    enabled: true,
    Lx: 40,
    Ly: 24,
    ridge: "X",
    pitch: 4,
    roofRise: 4,
    lines: [
      { id: "LN1", name: "Line 1 (front)", storyId: "ST1", dir: "X", trib: 12, pos: 0 },
      { id: "LN2", name: "Line 2 (rear)", storyId: "ST1", dir: "X", trib: 12, pos: 24 },
      { id: "LNA", name: "Line A (left)", storyId: "ST1", dir: "Y", trib: 20, pos: 0 },
      { id: "LNB", name: "Line B (right)", storyId: "ST1", dir: "Y", trib: 20, pos: 40 },
    ],
    distribution: "envelope",
  };
  p.lateral.stories[0].items = generateWeights(p, p.lateral, 0);
  return p;
}
