/**
 * Example project: one-story wood-framed residence, 24 ft deep, raised floor.
 * Rafters with a ridge board tied by the ceiling joists, a window header
 * carrying the rafter and ceiling joist reactions, floor joists on a girder,
 * and an I-joist floor bay. Used for first-run, tests and the help sheet.
 */

import { defaultAssemblies } from "../loads/dead";
import { DEFAULT_MARKS } from "./marks";
import type { Project } from "./schema";

export function newProject(name = "New project"): Project {
  return {
    schemaVersion: 1,
    info: {
      name,
      address: "",
      jobRef: "",
      client: "",
      jurisdiction: "",
      preparedBy: "",
      checkedBy: "",
      approvedBy: "",
      date: "",
      revision: "0",
    },
    cycleId: "2025",
    criteria: {
      riskCategory: "II",
      liveBasis: "IRC",
      roofLive: { L0: 20, reduce: false },
      snow: { pg: 0, Ce: 1.0, Ct: 1.0, Is: 1.0, slippery: false },
      Kcr: 1.0,
      seismic: { SDS: 1.0, SD1: 0.6, siteClass: "D (default)", SDC: "D" },
      wind: { V: 95, exposure: "B", Kzt: 1.0 },
      soil: { bearing: 1500, source: "Presumptive, CBC Table 1806.2 — verify with geotechnical report" },
    },
    assemblies: defaultAssemblies(),
    structures: [
      {
        id: "S1",
        name: "Main house",
        levels: [
          { id: "L1", name: "First floor", number: 1 },
          { id: "RF", name: "Roof", number: 2 },
        ],
      },
    ],
    members: [],
    marks: { ...DEFAULT_MARKS },
    drawings: [],
    review: [],
    notes: "",
  };
}

export function exampleProject(): Project {
  const p = newProject("Example Residence");
  p.info = {
    ...p.info,
    address: "123 Example Street, Escondido, CA",
    jobRef: "HC-0001",
    client: "Example Owner",
    jurisdiction: "City of Escondido",
    date: "2026-10-07",
  };
  p.members = [
    {
      kind: "rafter",
      id: "m-r1",
      mark: "R-1",
      description: "Main roof rafters, ridge board, tied by CJ-1",
      structureId: "S1",
      levelId: "RF",
      status: "new",
      links: [],
      species: "DF-L",
      grade: "No.2",
      size: "2x8",
      spacing: 24,
      rise: 4,
      run: 12,
      overhang: 1.5,
      ridge: "board",
      plateSeat: 5.5,
      ridgeSeat: 0,
      seatCut: 1.5,
      dead: { assemblyId: "RD1" },
      roofLive: true,
      snow: true,
      deflection: { preset: "roof-nonplaster" },
      luBottom: 4,
      rule441: false,
      tieSpacing: 24,
      gable: true,
    },
    {
      kind: "ceilingJoist",
      id: "m-cj1",
      mark: "CJ-1",
      description: "Ceiling joists / rafter ties, lapped over the center bearing wall",
      structureId: "S1",
      levelId: "RF",
      status: "new",
      links: [],
      species: "DF-L",
      grade: "No.2",
      size: "2x6",
      spacing: 24,
      spans: [12, 12],
      dead: { assemblyId: "CD1" },
      live: { use: "attic-no-storage" },
      extra: [],
      bearing: [5.5, 3.5, 5.5],
      deflection: { preset: "roof-nonplaster" },
      luTop: 0,
      rule441: true,
      tensionFrom: "m-r1",
      heel: { nail: "16d-common", count: 8, rafterThickness: 1.5 },
    },
    {
      kind: "beam",
      id: "m-h1",
      mark: "H-1",
      description: "Window header, exterior bearing wall",
      structureId: "S1",
      levelId: "L1",
      status: "new",
      links: [
        { id: "k1", kind: "line", sourceId: "m-r1", support: 0, label: "Rafters", factor: 1 },
        { id: "k2", kind: "line", sourceId: "m-cj1", support: 0, label: "Ceiling joists", factor: 1 },
      ],
      role: "header",
      material: { kind: "sawn", species: "DF-L", grade: "No.2", size: "4x8", plies: 1 },
      spans: [6],
      area: [],
      walls: [],
      extra: [],
      bearing: [3, 3],
      luTop: 0,
      luBottom: 0,
      deflection: { preset: "roof-nonplaster" },
      selfWeight: true,
    },
    {
      kind: "joist",
      id: "m-fj1",
      mark: "FJ-1",
      description: "Raised floor joists",
      structureId: "S1",
      levelId: "L1",
      status: "new",
      links: [],
      species: "DF-L",
      grade: "No.2",
      size: "2x10",
      spacing: 16,
      spans: [12],
      dead: { assemblyId: "FD1" },
      live: { use: "living" },
      extra: [],
      bearing: [1.5, 1.5],
      luBottom: 0,
      rule441: false,
      deflection: { preset: "floor" },
    },
    {
      kind: "beam",
      id: "m-b1",
      mark: "B-1",
      description: "Floor girder on posts, joists from both sides",
      structureId: "S1",
      levelId: "L1",
      status: "new",
      links: [{ id: "k3", kind: "line", sourceId: "m-fj1", support: 1, label: "Floor joists both sides", factor: 2 }],
      role: "beam",
      material: { kind: "sawn", species: "DF-L", grade: "No.1", size: "4x12", plies: 1 },
      spans: [6],
      area: [],
      walls: [],
      extra: [],
      bearing: [3.5, 3.5],
      luTop: 0,
      luBottom: 0,
      deflection: { preset: "floor" },
      selfWeight: true,
    },
    {
      kind: "ijoist",
      id: "m-ij1",
      mark: "IJ-1",
      description: "Family room I-joist bay",
      structureId: "S1",
      levelId: "L1",
      status: "new",
      links: [],
      series: "TJI 210",
      depth: '11-7/8"',
      spacing: 16,
      spans: [16],
      dead: { assemblyId: "FD1" },
      live: { use: "living" },
      extra: [],
      bearing: [1.75, 3.5],
      deflection: { preset: "floor" },
    },
  ];
  return p;
}
